const getImgSrc =  (path: string, filename: string, option? : { format?: string, size?: 'small'|'medium'|'large'|'xlarge'|'default' } ) => {
// const getImgSrc =  (path: string, filename: string, format?: string, size: 'small'|'medium'|'large'|'xlarge' = 'medium' ) => {
    /*  sunknudsen. (2020, Mar 27). How to use static media assets generated by CRA’s npm build in SSR mode?. StackOverflow.
     *  https://stackoverflow.com/questions/60874394/how-to-use-static-media-assets-generated-by-cra-s-npm-build-in-ssr-mode
     */
    // const basePath = `${window.ENV.PUBLIC_URL}/images`;
    const basePath = `/images`;
    // const basePath = `static/images`;
    
    return(
        `${basePath}${path}/${filename}${ option?.size === 'default' ? '' : `-${option?.size || "medium"}`}.${option?.format || FORMATWEBP}`
        // require(`../assets/images${path}/${filename}.${format}`).default
    )
}

const basePath = '/static/images';
const FORMATWEBP = 'webp';
const FORMATSVG ='svg'
const FORMATPNG ='png'
const FORMATJPG ='jpg'

export default getImgSrc;
export { basePath, FORMATSVG, FORMATWEBP, FORMATPNG, FORMATJPG };